<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <Title>MobaHinted Client</Title>
        <Authors>Ethan Henderson</Authors>
        <Description>A fast, ad-free League of Legends client. Beyond that, it is more reliable, lighter, open-source, packed with your favorite overlays plus brand new, fresh overlays coaches have been telling us to use the equivalent of for years.</Description>
        <PackageProjectUrl>https://mobahinted.app/</PackageProjectUrl>
        <RepositoryUrl>https://github.com/MobaHinted/client/</RepositoryUrl>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <LangVersion>13</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <!-- Most NuGets -->
    <ItemGroup>
        <PackageReference Include="MingweiSamuel.TokenBucket" Version="1.0.2.0"/>
        <PackageReference Include="Semi.Avalonia" Version="11.2.1.4"/>
        <PackageReference Include="Projektanker.Icons.Avalonia.FontAwesome" Version="9.6.0"/>
        <PackageReference Include="ReactiveUI.Validation" Version="4.1.1"/>
        <PackageReference Include="System.Drawing.Common" Version="9.0.2"/>
    </ItemGroup>

    <!-- Local Camille fork -->
    <ItemGroup Condition="'$(Configuration)'=='Debug'">
        <ProjectReference Include="../../Camille/src/Camille.Enums/Camille.Enums.csproj"/>
        <ProjectReference Include="../../Camille/src/Camille.RiotGames/Camille.RiotGames.csproj"/>
    </ItemGroup>
    <!-- Standard Camille -->
    <ItemGroup Condition="'$(Configuration)'!='Debug'">
        <PackageReference Include="Camille.Enums"
                          Version="3.0.0-nightly-2025-02-01-a17f385bca"/>
        <PackageReference Include="Camille.RiotGames"
                          Version="3.0.0-nightly-2025-02-01-a17f385bca"/>
    </ItemGroup>

    <!-- Avalonia -->
    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.4"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.2.4"/>
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.2.4"/>
    </ItemGroup>
</Project>
